kind: Service
apiVersion: v1
metadata:
  name: csi-sandstone-nfsplugin-provisioner
  labels:
    app: csi-sandstone-nfsplugin-provisioner
spec:
  selector:
    app: csi-sandstone-nfsplugin-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-sandstone-nfsplugin-provisioner
spec:
  serviceName: "csi-sandstone-nfsplugin-provisioner"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-sandstone-nfsplugin-provisioner
    spec:
      serviceAccount: nfs-csi-provisioner
      containers:
        - name: nfs-csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.0.1
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/sandstone-csi-nfsplugin/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/sandstone-csi-nfsplugin

        - name: sandstone-nfsplugin
          image: szsandstone/sandstone-nfsplugin:v1.0.0
          args :
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--v=5"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
      volumes:
        - name: socket-dir
          emptyDir:
